<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="getStatusbyCC"
     targetNamespace="http://oracle.com/sca/soapservice/POProcessing/ValidationforCC/getStatusbyCC"
     xmlns:tns="http://oracle.com/sca/soapservice/POProcessing/ValidationforCC/getStatusbyCC"
     xmlns:inp1="http://www.example.org"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org" schemaLocation="../Schemas/Creditcheck.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="Request" element="inp1:CreditcardStatusRequest"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="Response" element="inp1:CredirCardStatus"/>
    </wsdl:message>
    <wsdl:message name="faultMessage">
        <wsdl:part name="Fault" element="inp1:Error"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
            <wsdl:fault name="executefault" message="tns:faultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
